# Hot reload configuration for Air on Windows
root = "."
tmp_dir = "tmp"

[build]
  # Gunakan .exe extension untuk Windows
  cmd = "go build -o ./tmp/main.exe ."
  bin = "./tmp/main.exe"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true